package: cloud.lazycat.app.dokploy
version: 0.29.13
name: Dokploy
description: "A self-hosted application deployment platform running on LazyCat Playground Docker"
min_os_version: 1.5.0
author: Dokploy
license: Apache-2.0
homepage: https://github.com/Dokploy/dokploy
admin_only: true

unsupported_platforms:
  - ios
  - android
  - tvos

locales:
  zh:
    name: "Dokploy"
    description: "运行在懒猫 Playground Docker 上的自托管应用部署平台"
  en:
    name: "Dokploy"
    description: "A self-hosted application deployment platform running on LazyCat Playground Docker"

permissions:
  required:
    - net.internet
    - net.lan
    - net.host
    - compose.override
